name: Go

on:
  push:
    branches: [ "master", "develop"]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        versions: [ '1.16', '1.18', '1.19', '1.20' ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up
        uses: actions/setup-go@v3
        with:
            go-version: ${{ matrix.versions }}

      - name: Build
        run: |
          go mod tidy
          go build -v ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Test
        run: |
          go mod tidy
          go test -v -race -coverpkg=./... ./...
