name: Go

on:
  push:
    branches: [ "master", "develop"]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cache Go modules
        uses: actions/cache@preview
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-   

      - uses: actions/checkout@v3

      - name: Set up
        uses: actions/setup-go@v3
        with:
            go-version: 'stable'

      - name: Build
        run: |
          go mod tidy
          go build -v ./...

      - name: Test
        run: |
          go mod tidy
          go test -v -race -coverpkg=./... ./...

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2

  artifacts:
    needs: [ build, lint ]
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3

      - name: Set up
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'

      - name: Build main.go
        run: |
          go mod tidy
          go build ./cmd/main.go

      - name: Upload artifacts on GitHub
        uses: actions/upload-artifact@master
        with:
          name: main_bin
          path: ./main

      - name: Archive files
        run: |
          sudo apt-get update
          sudo apt-get install zip
          zip -r artifacts.zip ./main

      - name: Upload artifacts on GDrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.credentials }}
          filename: "artifacts.zip"
          folderId: ${{ secrets.folderId }}
          name: "artifacts.zip"
          overwrite: "true"