name: Go

on:
  push:
    branches: [ "master", "develop"]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up
        uses: actions/setup-go@v3
        with:
            go-version: 'stable'

      - name: Build
        run: |
          go mod tidy
          go build -v ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Test
        run: |
          go mod tidy
          go test -v -race -coverpkg=./... ./...
