name: Go

on:
  push:
    branches: [ "master", "develop"]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cache Go modules
        uses: actions/cache@preview
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-   

      - uses: actions/checkout@v3

      - name: Set up
        uses: actions/setup-go@v3
        with:
            go-version: 'stable'

      - name: Build
        run: |
          go mod tidy
          go build -v ./...
          go build ./cmd/main.go

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Test
        run: |
          go mod tidy
          go test -v -race -coverpkg=./... ./...

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: main.exe
          path: ./main.exe
